# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
